services:
  server1:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    networks:
      - servers

  server2:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8081:8080"
    networks:
      - servers

  server3:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8082:8080"
    networks:
      - servers

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "8083:8081"
    command: "db"
    networks:
      - servers
