version: "3.8"

services:
  server1:
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      - servers
    ports:
      - "8080:8080"

  server2:
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      - servers
    ports:
      - "8082:8080"  # змінив порт, щоб уникнути конфлікту

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    networks:
      - servers
    ports:
      - "8081:8081"  # це залишаємо для доступу до БД

  balancer:
    build:
      context: .
    command: "lb"
    networks:
      - servers
    ports:
      - "8090:8090"

networks:
  servers:
