version: "3.8"

services:
  server1:
    build: .
    networks:
      - servers
    ports:
      - "8080:8080"

  server2:
    build: .
    networks:
      - servers
    ports:
      - "8081:8080"

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    networks:
      - servers
    ports:
      - "8081:8081"

  balancer:
    build: .
    command: "lb"
    networks:
      - servers
    ports:
      - "8090:8090"

networks:
  servers:
